<?php
/**
 * @file
 * Integration code for kalendersiden.dk.
 */

/**
 * Adds menu for kalendersiden.
 *
 * Implements hook_menu().
 */
function vih_kalendersiden_menu() {
  $items = array();
  $items['kalender/pdf'] = array(
    'title' => 'PDF',
    'page callback' => 'vih_kalendersiden_view_pdf_form',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_ACTION,
    'description' => 'Create PDF',
  );

  $items['kalender/view'] = array(
    'title' => 'PDF',
    'page callback' => 'vih_kalendersiden_pdf_generate',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'description' => 'Create PDF',
  );

  $items['admin/config/services/kalendersiden'] = array(
    'title' => 'VIH kalendersiden.dk',
    'description' => 'Manage kalendersiden.dk settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vih_kalendersiden_admin_settings'),
    'access arguments' => array('administer vih kalendersiden'),
    'file' => 'vih_kalendersiden.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function vih_kalendersiden_permission() {
  return array(
    'administer vih kalendersiden' => array(
    'title' => t('administer vih kalendersiden'),
    'description' => t('Administer settings for VIH kalendersiden.dk'),
    ),
  );
}

/**
 * Method to call kalendersiden options.
 */
function vih_kalendersiden_view_pdf_form() {
  return drupal_get_form('vih_kalendersiden_form');
}

/**
 * Form for kalendersiden.
 */
function vih_kalendersiden_form($form_state) {
  drupal_set_title('Create calendar PDF');

  $form['#method'] = 'POST';

  $form['vih_kalendersiden'] = array(
    '#type' => 'fieldset',
    '#title' => t('Settings for the PDF calendar'),
    '#tree' => TRUE,
  );

  $months = array(
    1 => t('January'),
    2 => t('February'),
    3 => t('March'),
    4 => t('April'),
    5 => t('May'),
    6 => t('June'),
    7 => t('July'),
    8 => t('August'),
    9 => t('September'),
    10 => t('October'),
    11 => t('November'),
    12 => t('December')
  );

  $form['vih_kalendersiden']['month'] = array(
    '#type' => 'select',
    '#title' => t('Starting month'),
    '#required' => TRUE,
    '#options' => $months,
    '#default_value' => date('n'),
  );

  $form['vih_kalendersiden']['months'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of months'),
    '#required' => TRUE,
    '#default_value' => 6,
  );

  $form['vih_kalendersiden']['year'] = array(
    '#type' => 'textfield',
    '#title' => t('Starting year'),
    '#required' => TRUE,
    '#default_value' => date('Y'),
  );

  $form['vih_kalendersiden']['pages'] = array(
    '#type' => 'textfield',
    '#title' => t('Printed on number of pages'),
    '#required' => TRUE,
    '#default_value' => 1,
  );

  $form['vih_kalendersiden']['format'] = array(
    '#type' => 'select',
    '#title' => t('Format'),
    '#required' => TRUE,
    '#options' => array(
      'landscape' => t('Landscape'),
      'portrait' => t('Portrait'),
    ),
    '#default_value' => 'landscape',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Get PDF'),
  );

  return $form;
}

/**
 * Validates input from form.
 *
 * @todo write validation functions
 *
 * Implements hook_form_validate().
 */
function vih_kalendersiden_form_validate($form, &$form_state) {
  /*
  if (intval($form_state['values']['vih_kalendersiden']['month']) > 0 ) {
    form_set_error('', t('Unknown format.'));
  }
  if (!in_array(array($form_state['values']['vih_kalendersiden']['format'], 'landscape', 'portrait'))) {
    form_set_error('', t('Unknown format.'));
  }
  */
}

/**
 * Implements hook_form_submit().
 */
function vih_kalendersiden_form_submit($form, &$form_state) {
  $year = check_plain(intval($form_state['values']['vih_kalendersiden']['year']));
  $month = check_plain(intval($form_state['values']['vih_kalendersiden']['month']));
  $months = check_plain(intval($form_state['values']['vih_kalendersiden']['months']));
  $pages = check_plain(intval($form_state['values']['vih_kalendersiden']['pages']));
  $format = check_plain($form_state['values']['vih_kalendersiden']['format']);

  $form_state['redirect'] = "kalender/view/$month/$year/$months/$pages/$format";
}

/**
 * Posts data from a view to kalendersiden.dk and gets the pdf created
 *
 * @param $month integer Month number
 * @param $year integer Year
 * @param $months integer Number of months to show
 * @param $pages integer Number of pages to distribute the number of months to
 * @param $format string Either landscape or portrait
 * 
 * @return string Delivers the PDF
 */
function vih_kalendersiden_pdf_generate($month = 3, $year = 2012, $months = 4, $pages = 1, $format = 'landscape') {
  $result = views_get_view_result('vih_calendar', NULL);

  $events = array();

  foreach ($result as $event) {
    if (date('dmY', strtotime($event->field_field_date[0]['raw']['value'])) != date('dmY', strtotime($event->field_field_date_1[0]['raw']['value2']))) {
      $events[] = 'fra ' .  date('d.m.Y ', strtotime($event->field_field_date[0]['raw']['value'])) . 'til ' . date('d.m.Y:', strtotime($event->field_field_date[0]['raw']['value2'])) . $event->node_title;
    }
    else {
      $events[] = date('d.m.Y: ', strtotime($event->field_field_date[0]['raw']['value'])) . ' ' . $event->node_title;
    }
  }

  $event_data = implode("\n", $events);

  $data = array(
    'month' => $month,
    'year' => $year,
    'months' => $months,
    'pages' => $pages,
    'format' => $format,
    'head' => variable_get('vih_kalendersiden_headline'),
    'userdata' => $event_data,
  );


  $array = array();

  foreach ($data as $key => $value) {
    $array[] = $key . '=' . rawurlencode($value);
  }

  $array[] = 'info[]=showyear';
  $array[] = 'info[]=holidays';
  $array[] = 'info[]=weeks';

  $post = implode('&', $array);

  $options = array(
    'method' => 'POST',
    'data' => $post,
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );

  $url = 'http://kalendersiden.dk/generate.php';

  $result = drupal_http_request($url, $options);

  drupal_add_http_header('Cache-Control', 'must-revalidate, post-check=0, pre-check=0');
  drupal_add_http_header('Content-type', 'application/pdf');
  drupal_add_http_header('content-disposition', 'attachment; filename="vih-kalender-' . check_plain($year) . '-' . check_plain($month) . '.pdf');
  print $result->data;
  exit();
}
