<?php
/**
 * @file
 */

/**
 * Implements hook_menu()
 */
function vih_kalendersiden_menu() {
  $items = array();  
  $items['kalender/pdf'] = array(
    'title' => 'PDF',
    'page callback' => 'vih_kalendersiden_pdf',
    'page arguments' => array(1),
    'access callback' => 'vih_kalendersiden_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_ACTION,    

  );  
  return $items;
}

/**
 * Checks permissions
 *
 * Everybody should be able to get the pdf
 */
function vih_kalendersiden_access($node) {
  return true;
}

/**
 * Posts data from a view to kalendersiden.dk and gets the pdf created
 */
function vih_kalendersiden_pdf() {
  $result = views_get_view_result('vih_calendar', $display_id);

  $events = array();

  foreach ($result as $event) {
    if (date('dmY', strtotime($event->field_field_date[0]['raw']['value'])) !=  date('dmY', strtotime($event->field_field_date_1[0]['raw']['value2']))) {
      $events[] = 'fra ' .  date('d.m. ', strtotime($event->field_field_date[0]['raw']['value'])) . 'til ' . date('d.m.:', strtotime($event->field_field_date[0]['raw']['value2'])) . $event->node_title;
    } 
    else {
      $events[] = date('d.m.: ', strtotime($event->field_field_date[0]['raw']['value'])) . ' ' . $event->node_title;
    } 
  }

  $month = 3;
  $year = 2012;
  $months = 4;
  $pages = 1;
  $format = 'landscape';

  $event_data = implode("\n", $events);

  $data = array(
    'month' => $month,
    'year' => $year,
    'months' => $months,
    'pages' => $pages,
    'format' => $format,
    'head' => 'Vejle Idrætshøjskole',
    'userdata' => $event_data
  );


  $array = array();

  foreach ($data as $key => $value) {
    $array[] = $key . '=' . rawurlencode($value);
  }
  
  $array[] = 'info[]=showyear';
  $array[] = 'info[]=holidays';
  $array[] = 'info[]=weeks';
  
  $post = implode('&', $array);

  $options = array(
    'method' => 'POST',
    'data' => $post,
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded')
  );

  $url = 'http://kalendersiden.dk/generate.php';

  $result = drupal_http_request($url, $options);

  drupal_add_http_header('Content-type','application/pdf');
  drupal_add_http_header('content-disposition','attachment; filename="vih-kalender-' . check_plain($year) . '-' . check_plain($month) . '.pdf');
  
  echo $result->data;
}
